### ISSUE TITLE
Portable Brave Updater

### ISSUE THREAD

**Issue by BB69** [UndertakerBen/PorBraveUpd#1]
Hi there

Portable Brave Updater don't work anymore (since yesterday)!

Thanks in advance to solve the problem and best regards
Beat

[2021-06-24_031303.pdf](https://github.com/UndertakerBen/PorBraveUpd/files/6707544/2021-06-24_031303.pdf)

**Comment by UndertakerBen** [comment]
Thanks for the info that the updater no longer works.
The new version 1.2.5.0 fixes fetching the version.

**Comment by Sir-Ezequiel** [comment]
Try to update and it doesn't install brave
